### ISSUE TITLE
Automatic releases for release candidates in designated Discord channel

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/Northstar#294]
It would be nice if we could set up a way that automatically posts release candidates to a designated Discord channel in Northstar Discord, upon build.

This would streamline our testing workflow a lot, as currently one needs to manually upload release builds to a channel.

**Comment by GeckoEidechse** [comment]
@p0358 what's the hook/bot you currently use to publish r1o releases? ^^

**Comment by p0358** [comment]
it's a custom-written script in PowerShell since no existing actions were good enough for what we wanted, I can share it when the author agrees (so when he wakes up) (not that it's not gonna be open source eventually anways xD)

**Comment by p0358** [comment]
Sending build itself is
```yaml
      - id: DiscordSendArtifacts
        if: success()
        name: Send build to Discord
        run: ./.github/discord-webhook-file.ps1 ${{ env.ARTIFACTS_PATH }}
        env:
          CI_NUM: ${{ matrix.target }}#${{ github.run_number }}
```
The script
```powershell
param ($file_path)
$EXT_WHITELIST = "*.exe", "*.dll"
if ($DISCORD_HOOK -isnot [string]) {
    $DISCORD_HOOK = $env:DISCORD_HOOK
}
$DiscordArgs = @{}
$DiscordArgs.Add("username", "GitHub Actions")
$DiscordArgs.Add("avatar_url", "https://raw.githubusercontent.com/github/explore/2c7e603b797535e5ad8b4beb575ab3b7354666e1/topics/actions/actions.png")
# $DiscordArgs.Add("content", "`u{2705}CI Run $env:CI_NUM was a success!")
$DiscordArgs.Add("file1", $(Compress-Archive -Path $(Get-ChildItem -Path $file_path -Recurse -Include $EXT_WHITELIST) -PassThru -DestinationPath $env:FILE_NAME))
Invoke-RestMethod -Uri "$($DISCORD_HOOK)?wait=true" -Method Post -form $DiscordArgs -ContentType "multipart/form-data"
```
written by @OctoNezd

goes without saying you need to supply the env variables:
- DISCORD_HOOK
- ARTIFACTS_PATH

It does on the fly compress the whitelisted extensions from specified dir and uploads that zip file to the channel where the webhook is attached to
